[build]
publish = "."

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/apps"
to = "/app-store.html"
status = 200

[[redirects]]
from = "/apps/*"
to = "/app-store.html"
status = 200

[[redirects]]
from = "/iOS"
to = "/ios/"
status = 200

[[redirects]]
from = "/iOS/*"
to = "/ios/:splat"
status = 200

[[redirects]]
from = "/brew"
to = "/brew/"
status = 200

[[redirects]]
from = "/brew/*"
to = "/brew/:splat"
status = 200

[[redirects]]
from = "/account"
to = "https://accounts.roachnet.org/"
status = 301
force = true

[[redirects]]
from = "/account/*"
to = "https://accounts.roachnet.org/:splat"
status = 301
force = true

[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
