[build]
publish = "."

[[redirects]]
from = "/apps"
to = "/app-store.html"
status = 200

[[redirects]]
from = "/apps/*"
to = "/app-store.html"
status = 200

[[redirects]]
from = "/ios"
to = "/iOS/"
status = 301

[[redirects]]
from = "/ios/*"
to = "/iOS/:splat"
status = 301

[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
